all:
	latexmk -c && latexmk -bibtex -pdf paper.tex

clean:
	rm -f *.aux *.log *.out *.toc *.lof *.lot *.bbl *.blg *.synctex.gz *.fls *.fdb_latexmk *.nav *.snm *.vrb *.idx *.ind *.ilg *.glo *.gls *.acn *.acr *.alg *.xdy *.bcf *.run.xml

